services:
  authentik-server:
    container_name: authentik-server
    command: server
    networks:
      - caddy
    #ports:
      #- 127.0.0.1:9000:9000/tcp
      #- 127.0.0.1:9443:9443/tcp
    volumes:
      - ./data/media:/media
      - ./data/templates:/templates
      - geoip:/geoip
    env_file: .env
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      # WORKERS: 2
    restart: on-failure
    image: ghcr.io/goauthentik/server:2022.7.2
  authentik-worker:
    container_name: authentik-worker
    command: worker
    user: root
    networks:
      - caddy
    volumes:
      - ./data/media:/media
      - ./data/templates:/templates
      - ./data/certs:/certs
      - geoip:/geoip
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
    restart: on-failure
    image: ghcr.io/goauthentik/server:2022.7.2
  redis:
    networks:
      - caddy
    restart: on-failure
    image: redis:alpine
  postgres:
    networks:
      - caddy
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    restart: on-failure
    image: postgres:12-alpine
  geoip:
    networks:
      - caddy
    volumes:
      - geoip:/usr/share/GeoIP
    env_file: .env
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=8
    restart: on-failure
    image: maxmindinc/geoipupdate:latest

volumes:
  geoip:
    driver: local

networks:
  caddy:
    external: true
